project:
  type: website
  output-dir: docs

website:
  title: "EnerData"
  navbar:
    tools:
      - icon: github
        url: https://github.com/EnerData
    background: light
    logo: enerdatalogo.png
    search: True
    left:
      - historias.qmd
      - tutoriales.qmd
      - index.qmd
      - integrantes.qmd
  page-footer: "Copyright 2024, G. Barrios" 

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: darkly
    css: styles.css
    toc: true



