project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-WWRVF9EZNE"
  title: "EnerData"
  navbar:
    tools:
      - icon: github
        url: https://github.com/EnerDataMx
    background: light
    logo: enerdatalogo.png
    search: True
    left:
      - historias.qmd
      - tutoriales.qmd
 #     - galeria.qmd
      - integrantes.qmd
  page-footer:  "This work is licensed under CC BY-NC 4.0 "
format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: darkly
    css: styles.css
    toc: true
lang: es    




