project:
  type: website
  output-dir: docs

website:
  title: "DataLab"
  page-footer: "Copyright 2024, G. Barrios" 
  navbar:
    tools:
      - icon: github
        url: https://github.com/AltamarMx
    background: primary
    logo: enerdatalogo.png
    search: True
    left:
      - text: "EnerData"
        menu: 
          - index.qmd
          - reglamento.qmd
      - investigacion.qmd
      - docencia.qmd
      - proyectos.qmd
      - dispositivos.qmd
      - integrantes.qmd
      - posts.qmd

format:
  html:
    theme: 
      dark: spacelab
      light: sketchy
    css: styles.css
    toc: true



